# # Site settings
# title: Gokulanand (Gokul) Iyer
# description: Engineer and math & physics enthusiast
# url: "https://gokulanand.github.io"
# baseurl: ""

# # Theme
# theme: minima

# # Minima settings
# minima:
#   skin: dark   # Enables dark mode

# # Navigation (top header links)
# header_pages:
#   - about.md
#   - projects.md

# # Social links (Minima supports these)
# minima:
#   social_links:
#     - { platform: github,  user_url: "https://github.com/YOUR_GITHUB" }
#     - { platform: linkedin, user_url: "https://www.linkedin.com/in/gokulanand-iyer-588613113/" }

# # Clean URLs (optional but recommended)
# permalink: /:title/

# # Build settings
# markdown: kramdown
# highlighter: rouge

# # Exclude unnecessary files from build
# exclude:
#   - README.md
#   - LICENSE



# site configuration

theme: jekyll-theme-chirpy

lang: en

# https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/New_York

# jekyll-seo-tag settings â€º https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

# main title
title: Gokul Iyer

# subtitle
tagline: Engineer

# used by seo meta and the atom feed
description: personal page

# protocol & hostname for your site (it does not end with a '/')
url: https://gokulanandiyer.github.io

author:
  name: Gokul Iyer
  # sets the `author.url` property. helps Google to disambiguate the correct author of articles
  url: https://github.com/gokulanandiyer

github:
  username: gokulanandiyer
